
all:
	make -i -C IndexIntro -f Makefile.r68ppc
	make -i -C Intro -f Makefile.r68ppc
	make -i -C OffScreenIntro -f Makefile.r68ppc
	
clean:
	make -i -C IndexIntro -f Makefile.r68ppc clean
	make -i -C Intro -f Makefile.r68ppc clean 
	make -i -C OffScreenIntro -f Makefile.r68ppc clean