
CC=m68k-apple-macos-gcc
CXX=m68k-apple-macos-g++
#CC=powerpc-apple-macos-gcc
#CXX=powerpc-apple-macos-g++

CFLAGS= -I../../../../Headers
LDFLAGS=-lOpenGLUtility -lOpenGLLibrary -lglaux -lgltk  -lDrawSprocketLib -lContextualMenu -lm

OBJS=$(subst .c,.o,$(wildcard *.c)) $(subst .cpp,.o,$(wildcard *.cpp))

.cpp.o:
	$(CXX) $(CFLAGS) -c -o $@ $<
	
.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

all: $(OBJS)
	$(CC) -o backtrace.code.bin $(OBJS) $(LDFLAGS)
	$(HOME)/sdl2macos9/bin2app.sh backtrace
#	$(CC) -o backtrace $(OBJS) $(LDFLAGS)
#	$(HOME)/sdl2macos9/xcoff2app.sh backtrace

clean:
	rm -f *.o *.bin *.pef *.APPL *.dsk *.gdb backtrace
