
all:
	make -C aux -f Makefile.r68ppc
	make -C glut -f Makefile.r68ppc
	make -C glu -f Makefile.r68ppc
	make -C mui -f Makefile.r68ppc
	make -C tk -f Makefile.r68ppc
	cp */*.a .

install:
	make -f Makefile.r68ppc
	cp *.a $(HOME)/Retro68-build/toolchain/powerpc-apple-macos/lib/.

clean:
	make -C aux -f Makefile.r68ppc clean
	make -C glut -f Makefile.r68ppc clean
	make -C glu -f Makefile.r68ppc clean
	make -C mui -f Makefile.r68ppc clean
	make -C tk -f Makefile.r68ppc clean
	rm -f *.a
