
all:
	make -C aux -f Makefile.r68
	make -C glut -f Makefile.r68
	make -C glu -f Makefile.r68
	make -C mui -f Makefile.r68
	make -C tk -f Makefile.r68
	cp */*.a .

install:
	make -f Makefile.r68
	cp *.a $(HOME)/Retro68-build/toolchain/m68k-apple-macos/lib/.

clean:
	make -C aux -f Makefile.r68 clean
	make -C glut -f Makefile.r68 clean
	make -C glu -f Makefile.r68 clean
	make -C mui -f Makefile.r68 clean
	make -C tk -f Makefile.r68 clean
	rm -f *.a
