
all:
	make -i -C aux -f Makefile.r68
	make -i -C glut -f Makefile.r68
	make -i -C Intros -f Makefile.r68
	make -i -C Multi-Texture\ CVA -f Makefile.r68
	make -i -C DrawSprocket -f Makefile.r68
	make -i -C Renderer\ Info -f Makefile.r68
	
clean:
	make -i -C aux -f Makefile.r68 clean
	make -i -C glut -f Makefile.r68 clean
	make -i -C Intros -f Makefile.r68 clean
	make -i -C Multi-Texture\ CVA -f Makefile.r68 clean
	make -i -C DrawSprocket -f Makefile.r68 clean
	make -i -C Renderer\ Info -f Makefile.r68 clean
