
all:
	make -i -C aux
	make -i -C glut
	make -i -C Intros
	make -i -C Multi-Texture\ CVA
	make -i -C DrawSprocket
	make -i -C Renderer\ Info
	
clean:
	make -i -C aux clean
	make -i -C glut clean
	make -i -C Intros clean
	make -i -C Multi-Texture\ CVA clean
	make -i -C DrawSprocket clean
	make -i -C Renderer\ Info clean
