
all:
	make -C atlantis -f Makefile.r68
#	make -i -C backtrace -f Makefile.r68
#	make -i -C book -f Makefile.r68
#	make -i -C samples -f Makefile.r68
	
clean:
	make -C atlantis  -f Makefile.r68 clean
	make -C backtrace  -f Makefile.r68 clean
	make -C book  -f Makefile.r68 clean
	make -C samples  -f Makefile.r68 clean
	rm -rf */*.o
