
all:
#	make -C atlantis -f Makefile.r68ppc
#	make -i -C backtrace -f Makefile.r68ppc
#	make -i -C book -f Makefile.r68ppc
#	make -i -C samples -f Makefile.r68ppc
	
clean:
	make -C atlantis  -f Makefile.r68ppc clean
	make -C backtrace  -f Makefile.r68ppc clean
	make -C book  -f Makefile.r68ppc clean
	make -C samples  -f Makefile.r68ppc clean
	rm -rf */*.o
