
all:
	make -i -C atlantis
	make -i -C backtrace
	make -i -C book
	make -i -C samples
	
clean:
	make -i -C atlantis clean
	make -i -C backtrace clean
	make -i -C book clean
	make -i -C samples clean
	rm -rf */*.o
