
all:
	make -i -C atlantis -f Makefile.r68
	make -i -C bluepony -f Makefile.r68
	make -i -C chess -f Makefile.r68
	make -i -C geoface -f Makefile.r68
	make -i -C glflare -f Makefile.r68
	make -i -C gliq -f Makefile.r68
	make -i -C glutmech -f Makefile.r68
	make -i -C ideas -f Makefile.r68
	make -i -C OpenGL\ logo -f Makefile.r68
	make -i -C perf\ harness -f Makefile.r68
	make -i -C raceGL -f Makefile.r68
	make -i -C roller\ coaster -f Makefile.r68
	make -i -C skyfly -f Makefile.r68
	make -i -C underwater -f Makefile.r68
	make -i -C walker -f Makefile.r68
	make -i -C yacme -f Makefile.r68
	make -i -C mui -f Makefile.r68
	
clean:
	make -i -C atlantis -f Makefile.r68 clean
	make -i -C bluepony -f Makefile.r68 clean
	make -i -C chess -f Makefile.r68 clean
	make -i -C geoface -f Makefile.r68 clean
	make -i -C glflare -f Makefile.r68 clean
	make -i -C gliq -f Makefile.r68 clean
	make -i -C glutmech -f Makefile.r68 clean
	make -i -C ideas -f Makefile.r68 clean
	make -i -C OpenGL\ logo -f Makefile.r68 clean
	make -i -C perf\ harness -f Makefile.r68 clean
	make -i -C raceGL -f Makefile.r68 clean
	make -i -C roller\ coaster -f Makefile.r68 clean
	make -i -C skyfly -f Makefile.r68 clean
	make -i -C underwater -f Makefile.r68 clean
	make -i -C walker -f Makefile.r68 clean
	make -i -C mui -f Makefile.r68 clean
	rm -rf */*.o
