
all:
	make -C atlantis -f Makefile.r68ppc
	make -C bluepony -f Makefile.r68ppc
	make -C chess -f Makefile.r68ppc
	make -C geoface -f Makefile.r68ppc
	make -C glflare -f Makefile.r68ppc
	make -C gliq -f Makefile.r68ppc
	make -C glutmech -f Makefile.r68ppc
	make -C ideas -f Makefile.r68ppc
	make -C OpenGL\ logo -f Makefile.r68ppc
	make -C perf\ harness -f Makefile.r68ppc
	make -C raceGL -f Makefile.r68ppc
	make -C roller\ coaster -f Makefile.r68ppc
	make -C skyfly -f Makefile.r68ppc
	make -C underwater -f Makefile.r68ppc
	make -C walker -f Makefile.r68ppc
	make -C yacme -f Makefile.r68ppc
	make -C mui -f Makefile.r68ppc
	
clean:
	make -C atlantis -f Makefile.r68ppc clean
	make -C bluepony -f Makefile.r68ppc clean
	make -C chess -f Makefile.r68ppc clean
	make -C geoface -f Makefile.r68ppc clean
	make -C glflare -f Makefile.r68ppc clean
	make -C gliq -f Makefile.r68ppc clean
	make -C glutmech -f Makefile.r68ppc clean
	make -C ideas -f Makefile.r68ppc clean
	make -C OpenGL\ logo -f Makefile.r68ppc clean
	make -C perf\ harness -f Makefile.r68ppc clean
	make -C raceGL -f Makefile.r68ppc clean
	make -C roller\ coaster -f Makefile.r68ppc clean
	make -C skyfly -f Makefile.r68ppc clean
	make -C underwater -f Makefile.r68ppc clean
	make -C walker -f Makefile.r68ppc clean
	make -C yacme -f Makefile.r68ppc clean
	make -C mui -f Makefile.r68ppc clean
	rm -rf */*.o
