
all:
	make -i -C atlantis
	make -i -C bluepony
	make -i -C chess
	make -i -C geoface
	make -i -C glflare
	make -i -C gliq
	make -i -C glutmech
	make -i -C ideas
	make -i -C OpenGL\ logo
	make -i -C perf\ harness
	make -i -C raceGL
	make -i -C roller\ coaster
	make -i -C skyfly
	make -i -C underwater
	make -i -C walker
	
clean:
	make -i -C atlantis clean
	make -i -C bluepony clean
	make -i -C chess clean
	make -i -C geoface clean
	make -i -C glflare clean
	make -i -C gliq clean
	make -i -C glutmech clean
	make -i -C ideas clean
	make -i -C OpenGL\ logo clean
	make -i -C perf\ harness clean
	make -i -C raceGL clean
	make -i -C roller\ coaster clean
	make -i -C skyfly clean
	make -i -C underwater clean
	make -i -C walker clean
	rm -rf */*.o
