
#CC=m68k-apple-macos-gcc
#CXX=m68k-apple-macos-g++
CC=powerpc-apple-macos-gcc
CXX=powerpc-apple-macos-g++

CFLAGS= -I../../../../../Headers -I../../../../../Headers/MUI
LDFLAGS=-lOpenGLUtility -lOpenGLLibrary -lglut -lmui -lDrawSprocketLib -lContextualMenu -lm

OBJS=$(subst .c,.o,$(wildcard *.c))

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

all: $(OBJS)
#	$(CC) -o bluepony.code.bin $(OBJS) $(LDFLAGS)
	$(CC) -o calc $(OBJS) $(LDFLAGS)
	$(HOME)/sdl2macos9/xcoff2app.sh calc

clean:
	rm -f *.o *.bin *.pef *.APPL *.dsk *.gdb calc
