
all:
	make -C Libraries -fMakefile.r68ppc
	make -C Libraries -fMakefile.r68ppc lib
	make -C Examples -fMakefile.r68ppc
	
clean:
	make -C Libraries -fMakefile.r68ppc clean
	make -C Examples -fMakefile.r68ppc clean
